apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: htmlrep-ingress
spec:
  replicas: 3
  selector:
    matchLabels:
      name: htmlrep-ingress
  template:
    metadata:
      name: htmlrep-ingress
      labels:
        name: htmlrep-ingress
    spec:
      containers:
        - name: htmlrep-ingress
          image: musfirotus/html-static:v2
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: htmlserv-ingress
spec:
  selector:
    name: htmlrep-ingress
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: htmlnets-ingress
  labels:
    name: htmlnets-ingress
spec:
  rules:
    - host: fira.cv.local
      http:
        paths:
          - path: /
            backend:
              serviceName: htmlserv-ingress
              servicePort: 80
