apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    tipe: nginx-rc
  annotations:
    description: Replication controller pertama yg kubuat
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 0
          #   periodSeconds: 10
          #   failureThreshold: 3
          #   successThreshold: 1
          #   timeoutSeconds: 1
